import { ApprovalRequiredError, ConflictError, ProviderError } from "../shared/errors.js";
import { sha256 } from "../shared/canonical.js";

export class VideoService {
  constructor({ repository, provider, storage }) {
    this.repository = repository;
    this.provider = provider;
    this.storage = storage;
  }

  async execute({ actionId, agentName = "marketer" }) {
    const original = await this.repository.requireAction(actionId);
    if (original.agentName !== agentName || original.actionType !== "video-render") {
      throw new ConflictError("Only the requesting Marketer may execute this video action");
    }
    if (original.status === "EXECUTED") return { action: original, replayed: true };
    if (original.approvalStatus !== "APPROVED") throw new ApprovalRequiredError();
    const { action, claimed } = await this.repository.claimForExecution(actionId);
    if (!claimed) throw new ApprovalRequiredError();
    const payload = await this.repository.getPayload(actionId);
    const outputs = [];
    let incurredCostMicrodollars = 0;
    try {
      for (const output of payload.outputs) {
        const generated = await this.provider.generate({
          prompt: output.prompt,
          aspectRatio: output.aspectRatio,
          durationSeconds: payload.durationSeconds,
          resolution: payload.resolution,
          generateAudio: payload.generateAudio,
        });
        if (
          !Number.isSafeInteger(generated.providerCostMicrodollars) ||
          generated.providerCostMicrodollars < 0
        ) {
          throw new ProviderError("Veo returned an invalid provider cost");
        }
        incurredCostMicrodollars += generated.providerCostMicrodollars;
        const generatedHash = sha256(generated.body);
        const objectKey = `epyhia-demo/${action.tenantId}/${action.runId}/video/${action.id}-${output.variant}-${generatedHash}.mp4`;
        const stored = await this.storage.put({
          objectKey,
          body: generated.body,
          mimeType: generated.mimeType,
        });
        if (stored.contentHash !== generatedHash) {
          throw new ConflictError("Stored video content hash does not match generated bytes");
        }
        outputs.push({
          ...output,
          objectKey,
          contentHash: stored.contentHash,
          mimeType: generated.mimeType,
          providerReference: generated.providerReference,
          providerCostMicrodollars: generated.providerCostMicrodollars,
        });
      }
      const costMicrodollars = outputs.reduce(
        (total, output) => total + output.providerCostMicrodollars,
        0,
      );
      if (costMicrodollars > payload.estimatedCostMicrodollars) {
        throw new ConflictError("Veo cost exceeded the administrator-approved payload");
      }
      const completed = await this.repository.completeVideoRender({
        actionId,
        tenantId: action.tenantId,
        runId: action.runId,
        brandDocumentId: payload.brandDocumentId,
        outputs,
        providerCostMicrodollars: costMicrodollars,
      });
      return { action: completed, outputs, replayed: false };
    } catch (error) {
      const providerReportedCost = error?.details?.incurredCostMicrodollars;
      if (
        Number.isSafeInteger(providerReportedCost) &&
        providerReportedCost > 0
      ) {
        incurredCostMicrodollars += providerReportedCost;
      }
      await this.repository.failPaidAction({
        actionId,
        message: error.message,
        providerCostMicrodollars: incurredCostMicrodollars,
      });
      if (error instanceof ConflictError) throw error;
      throw new ProviderError("Approved Veo render failed", { cause: error.message });
    }
  }
}
